# Graph Convolutional Network to Overcome Navigation Challenges

By: Apurvata Kumar

Updated: March 2026

In [17]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from sklearn.preprocessing import MinMaxScaler

Change below file paths as needed.

In [18]:
# Import customized datasets
simple_file = '/content/custom_data_simple.csv'
# For both medium and complex datasets
complex_file = '/content/custom_data_complex.csv'

Using three types of datasets for three phases. I am commenting out the others when one dataset is in use.

In [19]:
# Create dataset for "simple" phase
df = pd.read_csv(simple_file).iloc[2:53]

# Convert longitude and latitude to integer for simple phase
df['usa_state_longitude'] = df['usa_state_longitude'].fillna(0).astype(int)
df['usa_state_latitude'] = df['usa_state_latitude'].fillna(0).astype(int)

# Select 5 rows at random for 10 different sets (8 for training and 2 for testing)
df_simple1 = df.sample(n=5)
df_simple2 = df.sample(n=5)
df_simple3 = df.sample(n=5)
df_simple4 = df.sample(n=5)
df_simple5 = df.sample(n=5)
df_simple6 = df.sample(n=5)
df_simple7 = df.sample(n=5)
df_simple8 = df.sample(n=5)
# For testing
df_simple9 = df.sample(n=5)
df_simple10 = df.sample(n=5)

display(df_simple1)
display(df_simple2)

   usa_state_code  usa_state_latitude  usa_state_longitude
40             RI                  41                  -71
10             GA                  32                  -82
50             WV                  38                  -80
11             HI                  19                 -155
18             LA                  31                  -92

   usa_state_code  usa_state_latitude  usa_state_longitude
2              AR                  35                  -91
51             WY                  43                 -107
18             LA                  31                  -92
3              AZ                  34                 -111
29             NE                  41                  -99

In [20]:
# Create dataset for "medium" phase
df = pd.read_csv(complex_file).iloc[2:246]

# Select 10 rows at random for 10 different sets (8 for training and 2 for testing)
df_medium1 = df.sample(n=10)
df_medium2 = df.sample(n=10)
df_medium3 = df.sample(n=10)
df_medium4 = df.sample(n=10)
df_medium5 = df.sample(n=10)
df_medium6 = df.sample(n=10)
df_medium7 = df.sample(n=10)
df_medium8 = df.sample(n=10)
# For testing
df_medium9 = df.sample(n=10)
df_medium10 = df.sample(n=10)

display(df_medium1)
display(df_medium2)

    country_code  country_latitude  country_longitude
62            EH         24.215527         -12.885834
209           TD         15.454166          18.732207
153           MX         23.634501        -102.552784
66            FI         61.924110          25.748151
7             AN         12.226079         -69.060087
228           UY        -32.522779         -55.765835
23            BI         -3.373056          29.918886
176           PM         46.941936         -56.271110
94            HN         15.199999         -86.241905
148           MS         16.742498         -62.187366

    country_code  country_latitude  country_longitude
150           MU        -20.348404          57.552152
153           MX         23.634501        -102.552784
200           SM         43.942360          12.457777
164           NP         28.394857          84.124008
205           SV         13.794185         -88.896530
186           RS         44.016521          21.005859
234           VI         18.335765         -64.896335
134           MA         31.791702          -7.092620
139           MH          7.131474         171.184478
67            FJ        -16.578193         179.414413

In [21]:
# Create dataset for "complex" phase
df = pd.read_csv(complex_file).iloc[2:246]

# Select 25 rows at random for 10 different sets (8 for training and 2 for testing)
df_complex1 = df.sample(n=25)
df_complex2 = df.sample(n=25)
df_complex3 = df.sample(n=25)
df_complex4 = df.sample(n=25)
df_complex5 = df.sample(n=25)
df_complex6 = df.sample(n=25)
df_complex7 = df.sample(n=25)
df_complex8 = df.sample(n=25)
# For testing
df_complex9 = df.sample(n=25)
df_complex10 = df.sample(n=25)

display(df_complex1)
display(df_complex2)

    country_code  country_latitude  country_longitude
151           MV          3.202778          73.220680
185           RO         45.943161          24.966760
235           VN         14.058324         108.277199
194           SG          1.352083         103.819836
15            AZ         40.143105          47.576927
119           KR         35.907757         127.766922
143           MN         46.862496         103.846656
211           TG          8.619543           0.824782
43            CL        -35.675147         -71.542969
241           YT        -12.827500          45.166244
84            GQ          1.650801          10.267895
167           NZ        -40.900557         174.885971
189           SA         23.885942          45.079162
57            DO         18.735693         -70.162651
31            BV        -54.423199           3.413194
188           RW         -1.940278          29.873888
72            GA         -0.803689          11.609444
62            EH         24.215527         -12.885834
77            GG         49.465691          -2.585278
136           MD         47.411631          28.369885
140           MK         41.608635          21.745275
170           PE         -9.189967         -75.015152
196           SI         46.151241          14.995463
221           TV         -7.109535         177.649330
208           TC         21.694025         -71.797928

    country_code  country_latitude  country_longitude
52            CZ         49.817492          15.472962
206           SY         34.802075          38.996815
219           TR         38.963745          35.243322
175           PL         51.919438          19.145136
90            GY          4.860416         -58.930180
119           KR         35.907757         127.766922
178           PR         18.220833         -66.590149
121           KY         19.513469         -80.566956
224           UA         48.379433          31.165580
42            CK        -21.236736        -159.777671
120           KW         29.311660          47.481766
198           SK         48.669026          19.699024
125           LC         13.909444         -60.978893
138           MG        -18.766947          46.869107
53            DE         51.165691          10.451526
139           MH          7.131474         171.184478
203           SR          3.919305         -56.027783
133           LY         26.335100          17.228331
29            BS         25.034280         -77.396280
99            IE         53.412910          -8.243890
76            GF          3.933889         -53.125782
40            CH         46.818188           8.227512
21            BG         42.733883          25.485830
181           PW          7.514980         134.582520
8             AO        -11.202692          17.873887

If any of the data points are null, we can rerun the code to regenerate random values that are not null.

***For the below code, the dataset can be changed to other simple or complex sets created above.***

As an example, only one dataset is used for the program.

In [22]:
# Pick a dataset
data = df_simple1

In [23]:
# Normalize datasets between the range [0, 1] using MinMaxScalar
scaler = MinMaxScaler()

df_simple1_norm = data.copy()
columns = ['usa_state_latitude', 'usa_state_longitude']
df_simple1_norm[columns] = scaler.fit_transform(df_simple1_norm[columns])

display(df_simple1_norm)

   usa_state_code  usa_state_latitude  usa_state_longitude
40             RI            1.000000             1.000000
10             GA            0.590909             0.869048
50             WV            0.863636             0.892857
11             HI            0.000000             0.000000
18             LA            0.545455             0.750000

In [24]:
# Convert (longitude, latitude) to cartesian coordinates (x, y)
df_simple1_cart = df_simple1_norm.copy()
df_simple1_cart['x'] = df_simple1_norm['usa_state_longitude']
df_simple1_cart['y'] = df_simple1_norm['usa_state_latitude']

df_simple1_cart = df_simple1_cart[['usa_state_code', 'x', 'y']].copy()

display(df_simple1_cart)

   usa_state_code         x         y
40             RI  1.000000  1.000000
10             GA  0.869048  0.590909
50             WV  0.892857  0.863636
11             HI  0.000000  0.000000
18             LA  0.750000  0.545455

This step converts the imported dataset into a custom normalized version using cartesian coordinates with values between 0 and 1.

In [25]:
# Add random noise to reduce overfitting
noise_val = 0.0003

df_simple1_cart['x'] = df_simple1_cart['x'] + np.random.normal(0, noise_val, size=len(data))
df_simple1_cart['y'] = df_simple1_cart['y'] + np.random.normal(0, noise_val, size=len(data))

display(df_simple1_cart)

   usa_state_code         x         y
40             RI  0.999532  1.000153
10             GA  0.868654  0.591335
50             WV  0.892502  0.863796
11             HI  0.000124 -0.000066
18             LA  0.749945  0.545595