# Graph Convolutional Network to Overcome Navigation Challenges

By: Apurvata Kumar

Updated: March 2026

In [36]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import csv
from sklearn.preprocessing import MinMaxScaler

Change below file paths as needed.

In [37]:
# Import customized datasets
simple_file = '/content/custom_data_simple.csv'
# For both medium and complex datasets
complex_file = '/content/custom_data_complex.csv'

Using three types of datasets for three phases. I am commenting out the others when one dataset is in use.

In [38]:
# Create dataset for "simple" phase
df = pd.read_csv(simple_file).iloc[2:53]

# Convert longitude and latitude to integer for simple phase
df['usa_state_longitude'] = df['usa_state_longitude'].fillna(0).astype(int)
df['usa_state_latitude'] = df['usa_state_latitude'].fillna(0).astype(int)

# Select 5 rows at random for 10 different sets (8 for training and 2 for testing)
df_simple1 = df.sample(n=5)
df_simple2 = df.sample(n=5)
df_simple3 = df.sample(n=5)
df_simple4 = df.sample(n=5)
df_simple5 = df.sample(n=5)
df_simple6 = df.sample(n=5)
df_simple7 = df.sample(n=5)
df_simple8 = df.sample(n=5)
# For testing
df_simple9 = df.sample(n=5)
df_simple10 = df.sample(n=5)

display(df_simple1)
display(df_simple2)

   usa_state_code  usa_state_latitude  usa_state_longitude
19             MA                  42                  -71
9              FL                  27                  -81
40             RI                  41                  -71
3              AZ                  34                 -111
11             HI                  19                 -155

   usa_state_code  usa_state_latitude  usa_state_longitude
21             ME                  45                  -69
32             NM                  34                 -105
43             TN                  35                  -86
47             VT                  44                  -72
44             TX                  31                  -99

In [39]:
# Create dataset for "medium" phase
df = pd.read_csv(complex_file).iloc[2:246]

# Select 10 rows at random for 10 different sets (8 for training and 2 for testing)
df_medium1 = df.sample(n=10)
df_medium2 = df.sample(n=10)
df_medium3 = df.sample(n=10)
df_medium4 = df.sample(n=10)
df_medium5 = df.sample(n=10)
df_medium6 = df.sample(n=10)
df_medium7 = df.sample(n=10)
df_medium8 = df.sample(n=10)
# For testing
df_medium9 = df.sample(n=10)
df_medium10 = df.sample(n=10)

display(df_medium1)
display(df_medium2)

    country_code  country_latitude  country_longitude
3             AG         17.060816         -61.796428
121           KY         19.513469         -80.566956
131           LU         49.815273           6.129583
91            GZ         31.354676          34.308825
214           TK         -8.967363        -171.855881
142           MM         21.913965          95.956223
152           MW        -13.254308          34.301525
145           MP         17.330830         145.384690
85            GR         39.074208          21.824312
37            CD         -4.038333          21.758664

    country_code  country_latitude  country_longitude
3             AG         17.060816         -61.796428
218           TO        -21.178986        -175.198242
172           PG         -6.314993         143.955550
90            GY          4.860416         -58.930180
110           JO         30.585164          36.238414
109           JM         18.109581         -77.297508
11            AS        -14.270972        -170.132217
76            GF          3.933889         -53.125782
156          NaN        -22.957640          18.490410
150           MU        -20.348404          57.552152

In [40]:
# Create dataset for "complex" phase
df = pd.read_csv(complex_file).iloc[2:246]

# Select 25 rows at random for 10 different sets (8 for training and 2 for testing)
df_complex1 = df.sample(n=25)
df_complex2 = df.sample(n=25)
df_complex3 = df.sample(n=25)
df_complex4 = df.sample(n=25)
df_complex5 = df.sample(n=25)
df_complex6 = df.sample(n=25)
df_complex7 = df.sample(n=25)
df_complex8 = df.sample(n=25)
# For testing
df_complex9 = df.sample(n=25)
df_complex10 = df.sample(n=25)

display(df_complex1)
display(df_complex2)

    country_code  country_latitude  country_longitude
173           PH         12.879721         121.774017
16            BA         43.915886          17.679076
90            GY          4.860416         -58.930180
54            DJ         11.825138          42.590275
206           SY         34.802075          38.996815
26            BN          4.535277         114.727669
128           LR          6.428055          -9.429499
213           TJ         38.861034          71.276093
107           IT         41.871940          12.567380
197           SJ         77.553604          23.670272
198           SK         48.669026          19.699024
93            HM        -53.081810          73.504158
141           ML         17.570692          -3.996166
180           PT         39.399872          -8.224454
187           RU         61.524010         105.318756
102           IN         20.593684          78.962880
62            EH         24.215527         -12.885834
160           NG          9.081999           8.675277
98            ID         -0.789275         113.921327
175           PL         51.919438          19.145136
220           TT         10.691803         -61.222503
34            BZ         17.189877         -88.497650
129           LS        -29.609988          28.233608
152           MW        -13.254308          34.301525
233           VG         18.420695         -64.639968

    country_code  country_latitude  country_longitude
25            BM         32.321384         -64.757370
225           UG          1.373333          32.290275
240           YE         15.552727          48.516388
143           MN         46.862496         103.846656
71            FR         46.227638           2.213749
21            BG         42.733883          25.485830
105           IR         32.427908          53.688046
43            CL        -35.675147         -71.542969
184           RE        -21.115141          55.536384
188           RW         -1.940278          29.873888
130           LT         55.169438          23.881275
114           KH         12.565679         104.990963
146           MQ         14.641528         -61.024174
140           MK         41.608635          21.745275
185           RO         45.943161          24.966760
179           PS         31.952162          35.233154
207           SZ        -26.522503          31.465866
221           TV         -7.109535         177.649330
227           US         37.090240         -95.712891
79            GI         36.137741          -5.345374
18            BD         23.684994          90.356331
20            BF         12.238333          -1.561593
31            BV        -54.423199           3.413194
137           ME         42.708678          19.374390
181           PW          7.514980         134.582520

If any of the data points are null, we can rerun the code to regenerate random values that are not null.

***For the below code, the dataset can be changed to other simple or complex sets created above.***

As an example, only one dataset is used for the program.

In [41]:
# Pick a dataset
data = df_simple1

In [42]:
# Normalize datasets between the range [0, 1] using MinMaxScalar
scaler = MinMaxScaler()

df_simple1_norm = data.copy()
columns = ['usa_state_latitude', 'usa_state_longitude']
df_simple1_norm[columns] = scaler.fit_transform(df_simple1_norm[columns])

display(df_simple1_norm)

   usa_state_code  usa_state_latitude  usa_state_longitude
19             MA            1.000000             1.000000
9              FL            0.347826             0.880952
40             RI            0.956522             1.000000
3              AZ            0.652174             0.523810
11             HI            0.000000             0.000000

In [43]:
# Convert (longitude, latitude) to cartesian coordinates (x, y)
df_simple1_cart = df_simple1_norm.copy()
df_simple1_cart['x'] = df_simple1_norm['usa_state_longitude']
df_simple1_cart['y'] = df_simple1_norm['usa_state_latitude']

df_simple1_cart = df_simple1_cart[['usa_state_code', 'x', 'y']].copy()

display(df_simple1_cart)

   usa_state_code         x         y
19             MA  1.000000  1.000000
9              FL  0.880952  0.347826
40             RI  1.000000  0.956522
3              AZ  0.523810  0.652174
11             HI  0.000000  0.000000

This step converts the imported dataset into a custom normalized version using cartesian coordinates with values between 0 and 1.

In [44]:
# Add random noise to reduce overfitting
noise_val = 0.0003

df_simple1_cart['x'] = df_simple1_cart['x'] + np.random.normal(0, noise_val, size=len(data))
df_simple1_cart['y'] = df_simple1_cart['y'] + np.random.normal(0, noise_val, size=len(data))

display(df_simple1_cart)

   usa_state_code         x         y
19             MA  1.000029  1.000070
9              FL  0.880987  0.347833
40             RI  0.999931  0.956481
3              AZ  0.524201  0.651852
11             HI -0.000169 -0.000230

After dataset is customized, the nodes (state or country codes) can be represented as a graph with edges (distance between nodes).

Note: The distance is inversed because farther distance has lower weights on the edges.

In [45]:
# Build a graph using nodes and edges